version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: doc/source/requirements-rtd.txt
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: doc/source/conf.py